esphome:
  name: gatecam
  friendly_name: gatecam

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FjCsDuivUDbddATQlRSX2o0dh58s9nbtvhqKq8/hlio="

ota:
  - platform: esphome
    password: "f095c32f51469ac6c2125333b508bd78"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.cowley.tech
  power_save_mode: NONE

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gatecam Fallback Hotspot"
    password: "T0pHjDo1mBsc"

captive_portal:

# Example configuration entry
web_server:

# Activates prometheus /metrics endpoint
prometheus:

esp32_camera:
  name: front_door_cam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  jpeg_quality: 10
  max_framerate: 10 fps

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

output:
  - platform: gpio
    pin: GPIO4
    id: led_output

light:
  - platform: binary
    name: "Camera Flash"
    output: led_output

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Gate Cam Button"
    id: gatecam_button

interval:
  - interval: 60s
    then:
      - if:
          condition:
            not:
              wifi.connected:
          then:
            - logger.log: "WiFi disconnected! Restarting WiFi..."
            - button.press: restart_device

button:
  - platform: restart
    name: "Restart Device"
    id: restart_device