esphome:
  name: gate
  friendly_name: gate

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Vk6VNCojQ5j8+bE/drTcPhIHKeWV7YCtFqiCjeDMYzc="

ota:
  - platform: esphome
    password: "01ca82e8daf83b16db832444db84b012"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.cowley.tech

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gate Fallback Hotspot"
    password: "eGErPbKoXQQg"

captive_portal:
    
web_server:

# Activates prometheus /metrics endpoint
prometheus:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
      inverted: True
      mode: 
        input: True
        pullup: True
    name: "Gate Sensor"
    id: gate_sensor