# esphome-entrypoint
esphome:
  name: panel01
  friendly_name: panel01

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  common: !include common/common.yaml

globals:
  - id: last_touch_time
    type: uint32_t
    restore_value: False
    initial_value: "0"
  - id: screen_dimmed
    type: bool
    initial_value: "false"

number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 15
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

# Create a Home Assistant blue color
color:
  - id: ha_blue
    hex: 51c0f2  # Blue color (for off state)
  - id: ha_yellow
    hex: FFA500 # Yellow color (for on state)

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm

spi:
  - id: spi_tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: spi_touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

display:
  - platform: ili9xxx
    model: ili9341
    id: my_display
    spi_id: spi_tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    dimensions: 
      height: 320
      width: 240
    transform: 
      swap_xy: True
      mirror_x: True
      mirror_y: True
    #rotation: 270
    invert_colors: false
    show_test_card: False
    color_palette: 8BIT
    color_order: RGB
    auto_clear_enabled: False
    #lambda: |-
    #  auto t = id(touch)->get_touch();
    #  if (t) // or touch.has_value()
    #    it.filled_circle(t.value().x, t.value().y, 10, ha_yellow);

    

touchscreen:
  - platform: xpt2046
    id: touch
    spi_id: spi_touch
    cs_pin: GPIO33
    transform: 
      swap_xy: False
      mirror_x: True
      mirror_y: False
    calibration: 
      x_max: 3718
      x_min: 187
      y_max: 3799
      y_min: 272
    on_release: 
      then:
        if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: backlight
    
time:
  - platform: homeassistant
    id: ha_time
  - platform: homeassistant
    id: antiburn_timer
    on_time:
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn

switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:



binary_sensor:
  - platform: homeassistant
    id: bedroom_lamp 
    entity_id: light.0x04e3e5fffe318927

    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: light_btn
          state:
            checked: !lambda return x;

one_wire:
  - platform: gpio
    pin: GPIO23

sensor:
  - platform: homeassistant
    id: office_target_temp
    entity_id: input_number.office_target_temperature
    on_value: 
      - lvgl.spinbox.update:
          id: office_temp_spinbox
          value: !lambda return x;
  - platform: dallas_temp
    id: panel01_temperature
    name: "Temperature"
    update_interval: 60s
    filters:
      - offset: -1.2
    on_value:
      then:
        - lvgl.label.update:
            id: ui_temp_label
            text: !lambda |-
              char buf[16];
              snprintf(buf, sizeof(buf), "%.1f°C", id(panel01_temperature).state);
              return std::string(buf);

lvgl:
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: backlight
      - lvgl.pause:
  theme: !include ui/theme.yaml
  style_definitions: !include ui/styles.yaml
  displays:
    - my_display
  touchscreens:
    - touch
  top_layer:
    widgets:
      - label:
          text: "\U000F05A9"
          id: lbl_hastatus
          hidden: true
          align: top_right
          x: -2
          y: 7
          text_align: right
          text_color: 0xFFFFFF
      - buttonmatrix:
          align: bottom_mid
          styles: header_footer
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: header_footer
          rows:
            - buttons:
              - id: page_prev
                text: "\U000F0141"
                on_press:
                  then:
                    lvgl.page.previous:
              - id: page_home
                text: "\U000F02DC"
                on_press:
                  then:
                    lvgl.page.show: home_page
              - id: page_next
                text: "\U000F0142"
                on_press:
                  then:
                    lvgl.page.next:
  pages: !include ui/pages.yaml
             
font: !include ui/fonts.yaml  


interval:
  - interval: 50ms
    then:
      - lambda: |-
          if (auto t = id(touch)->get_touch()) {
            // Filter out the bogus 0,0 noise
            if (t->x > 50 || t->y > 50) {
              id(backlight).turn_on();
              id(last_touch_time) = millis();
              ESP_LOGI("touch", "Valid touch: x=%d y=%d", t->x, t->y);
            }
          }

          // turn off after 15 seconds
          const uint32_t timeout = 15000;
          if (millis() - id(last_touch_time) > timeout) {
            id(backlight).turn_off();
          }


